### ISSUE TITLE
[PHP 7.2 nightly] DOMNodeComparator::assertEquals() bad method signature

### ISSUE THREAD

**Issue by claudiopro** [sebastianbergmann/comparator#32] opened 2017-01-29 15:38 UTC
Hi @sebastianbergmann,

I hit an issue with the signature of `DOMNodeComparator::assertEquals()` and PHP 7.2 nightly [found by Travis CI](https://travis-ci.org/emeraldion/creso/jobs/196352278), it seems the arguments don't match with `ObjectComparator::assertEquals()`:

```
Fatal error: Declaration of
SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false)
must be compatible with
SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array)
in phar:///home/travis/.phpenv/versions/master/bin/phpunit/sebastian-comparator/DOMNodeComparator.php
on line 0
```

PHP and Composer versions:

```sh
$ php --version
PHP 7.2.0-dev (cli) (built: Jan 28 2017 22:46:30) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0-dev, Copyright (c) 1999-2017, by Zend Technologies
$ composer --version
Composer version 1.3.2 2017-01-27 18:23:41
```

**Comment by sebastianbergmann** [comment] 2017-01-29 15:52
Duplicate of #30.

**Closed by sebastianbergmann** 2017-01-29 15:52 UTC

**Comment by claudiopro** [comment] 2017-01-29 15:55
Oh sorry, I couldn't find an issue in the queue so I opened it 😊  Thanks, I'll update to latest!

**Comment by rajesh2k8** [comment] 2018-04-19 12:50
Hello Friends, I am getting below errors:
 must be compatible with PHPUnit_Framework_Comparator_Object::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in C:\xampp\php\pear\PHPUnit\Framework\Comparator\DOMDocument.php on line 114

I did not get any solutions for same.

Please help me. Thanks!

**Comment by matthewjohnson2821** [comment] 2018-08-02 17:25
Same issue. Please help!!

**Comment by rajesh2k8** [comment] 2018-08-03 05:14
Please check your Zend version, Basically, I have the issue but due to some Zend framework version. Mistakenly I have installed Zend 3 framework and PHPUnit test cases written in Zend 2 framework.
Please once check. I hope your problem will get resolved.

While install the Zend framework give forcefully Zend version name so that you will get install exact version whatever you want.

Thanks

**Comment by baspeeters** [comment] 2019-08-07 19:32
Just ran into this issue in Symfony 4.3 while using `persist()` on an `ObjectManager` instance.

**Comment by MarcoConsiglio-Wichee** [comment] 2020-02-06 11:33
I found this error writing an assertion in a test;
```php
// Represent a Ticket through a custom class.
$ticket = new Ticket;
// Represent a Ticket through SimpleXMLElement.
$xml = new SimpleXMLElement("/path/to/xml");

// Put equal values in $ticket and $xml.

// Both the operand are string for sure.
$this->assertEquals($ticket->assigned_user_id, $xml->AssignedUserID);
```
I hope this can help to investigate the issue.
